### ISSUE TITLE
使用兄弟的  设备属性和启动参数 无法正常启动

### ISSUE THREAD

**Issue by 13631181823** [LINGJP/Hackintosh-Shinelon-T50TI-EFI#3]
使用兄弟的efi  config中设备属性和启动参数bootargs 无法正常启动
自行调换https://www.cmbs-soft.com/oc-stable-x1-x6ti-2-8-0/同模具的设备属性和启动参数可以。
希望兄弟多多帮忙看下。你的休眠正常，上面这个休眠不正常。
希望兄弟长期更新，毕竟遇到同机型的太不容易了。❤️❤️❤️❤️❤️

**Comment by LINGJP** [comment]
1080P自行重新尝试注入FB，我这没有测试条件
